# Deep vision prompting
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 1
  TEST:
    BATCH_SIZE: 200
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: []

OPTIM:
  NAME: "sgd"
  LR: 40.0
  MAX_EPOCH: 10
  LR_SCHEDULER: "cosine"


TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/32"

TRAINER:
  ZSROBUST:
    PREC: "fp16"
    VISUAL_PROMPT_METHOD: "padding"
    PROMPT_SIZE: 30
    ADD_PROMPT_SIZE: 5

ATTACK:
  PGD:
    EPS: 1
    ALPHA: 1
    TRAIN_ITER: 2
    TEST_ITER: 100

